add sort by email
ApostolaT/QuizApp pull request #29
Opened 2020-04-10 09:18 UTC by ApostolaT

2020-04-10 12:38 UTC, CalinBolea commented on src/Controllers/UserController.php
> +    private function createUrlParameters(array $filterParams, string $sortParam, string $searchParam): array
logica asta poate fi mutata in url helper, pare ca el ar trebui sa stie sa isi seteze parametrii interni in functie de argumentele `$filterParams, $sortParam, $searchParam`. De regula e o idee buna sa nu ai functii private sau protected in controllerele concrete. Daca ai metode private sau protected, de obicei e un semn ca exista ceva logica in controller care nu prea are ce cauta acolo.

2020-04-10 12:38 UTC, CalinBolea commented on src/Services/UserService.php
> +    public function getAll(int $page, array $filters = [], string $searchValue = "", $sortParams = ""): ?array
nu vad rostu acestei metode in `UserService`. Nu ai avea nevoie de ea daca ai muta logica de aici in repo-ul de user si ai folosi repo-ul in loc de service pentru call-ul asta. Cu genul asta de metode adaugi complexitate pe care va trebui sa o intretii fara vreo valoare pentru proiect. P.S. daca o muti in repo, redenumeste-o in ceva prefixat cu `find`, poate `findAll()`

2020-04-10 12:38 UTC, CalinBolea commented on src/Utils/UrlHelper.php
> +    /**
spacing. dupa fiecare atribut, constanta, use-uri de trait-uri sau metoda dintr-o clasa, urmeaza o linie goala, cu exceptia ultimului element din clasa. Te rog adauga linii goale dupa fiecare element din clasa asta.

2020-04-10 12:38 UTC, CalinBolea commented on src/Utils/UrlHelper.php
> +    public function setPaginator(Paginator $paginator)
return types la metode, chiar daca e void (cu exceptia metodelor magice, inclusiv constructorul). Te rog adauga la toate metodele din clasa.

2020-04-10 12:38 UTC, CalinBolea commented on src/views/admin-users-listing.phtml
> +                    <option value="user<?php echo $urlHelper->getUrlForFilter("role", "user");?>" <?php if($urlHelper->getValue("role") === 'user') echo "selected";?>>user</option>
logica de if-uri de pe liniile astea poate ar putea fi mutata in url helper, poate ceva gen `isSelected`

2020-04-10 12:38 UTC, CalinBolea commented on src/views/admin-users-listing.phtml
> +                        if ($urlHelper->getValue("sort") === "dsc"): echo "dsc"; endif;
nu-mi plac if-urile astea, dar nu stiu unde sa le pui acum, in url helper nu as zice ca ii locul lor, altfel de helper ti-ar trebui, dar nu il fa in scope-ul pull requestului astuia.

2020-04-10 12:38 UTC, CalinBolea commented on src/Utils/UrlHelper.php
> +        return "?page=".$this->paginator->getNextPage().http_build_query($this->urlParameters);
spacing. Un pic cam inghesuite toate elementele le linia asta, de regula se lasa un spatiu inainte si dupa operatorul de concatenare (e.x: $firstName . ' ' . $nickName . ' ' . $lastName`)

2020-04-13 07:13 UTC, calinpristavu commented on src/Controllers/UserController.php
> +        // Check if user has permission
😁 ok
the if is kinda self-explanatory.

However the controller methods are getting quite long, let's see if we can extract some functionality into separate classes

2020-04-13 07:17 UTC, calinpristavu requested changes

2020-04-13 07:17 UTC, calinpristavu commented on src/Controllers/UserController.php
> +        $sortParam = ($request->getParameter('sort')) ?? "";
a lot of paginator logic..

How about you add a static factory method on `Paginator` called `createFromRequest(Request $request): Paginator` or a factory class `PaginatorFactory` with `createFromRequest` and delegate creating the paginator to that

2020-04-13 15:41 UTC, CalinBolea requested changes

2020-04-13 15:41 UTC, CalinBolea commented on src/Utils/PaginatorTrait.php
> +        $totalResults = $service->countRows()["rows"];
AbstractService (urasc clasa asta) nu pare sa aiba in interfata ei (nici in abstracta) metoda `countRows()`. Type hint-ul pe care il folosesti pentru un obiect ar trebui sa contina metodele pe care le vei folosi de pe obiectul respectiv.

AbstractService nu inteleg de ce exista. E o clasa goala pur si simplu. Ori o pui sa faca ceva, ori o stergi. Daca o extinzi doar de dragu de a avea un type hint comun pentru toate serviciile, atunci macar fa o interfata goala (tehnica de a face o interfata goala pentru a putea type hint-ui pe anumite obiecte se numeste Marker Interface)

2020-04-13 15:41 UTC, CalinBolea commented on src/Utils/PaginatorTrait.php
> +        AbstractService $service,
same thing

2020-04-13 15:41 UTC, CalinBolea commented on src/Utils/UrlHelper.php
> +    /**
am vazut ca ai pus linii goale prin clasa, foarte bine, dar mai adauga una si intre proprietatile clasei, mai exact intre linia 16 si 17

2020-04-13 15:41 UTC, CalinBolea commented on src/Utils/UrlHelperTrait.php
> +trait UrlHelperTrait {
psr. Acolada dupa un trait se deschide pe linie noua.

2020-04-13 15:41 UTC, CalinBolea commented on src/Utils/UrlHelper.php
> +     * @return mixed|null
e string sau mixed|nul?

2020-04-13 15:41 UTC, CalinBolea commented on src/Utils/UrlHelper.php
> +    public function getValue(string $key): string
```suggestion
    public function getValue(string $key, string $default = ""): string
```

2020-04-13 15:41 UTC, CalinBolea commented on src/Utils/UrlHelper.php
> +            return "";
```suggestion
            return $default;
```

2020-04-14 14:49 UTC, merged